FROM openjdk:8-jdk-alpine
VOLUME /tmp
LABEL maintainer=marius.iancu@gmail.com
RUN apk add --no-cache openjdk8
COPY files/UnlimitedJCEPolicyJDK8/* /usr/lib/jvm/java-1.8-openjdk/jre/lib/security/
COPY target/*.jar app.jar
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/app.jar"]